added -I and -L to configure. help is now more verbose.
modified:
  configure
  src/build_config/config.mk

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -14,11 +14,34 @@ FEATURES="lock_on_write_graph_add"
 #
 # helper functions
 #
+
+# print help screen
 function print_help()
 {
-  echo "$0 [--prefix <path>] [--disable <plugin>] [--list-plugins] [--help] [--debug]" >&2
+  cat<<EOF >&2
+$0 options are:
+  [--prefix <path>]    prefix for the installation directory (1)
+  [--debug]            build in debug mode (2)
+  [--list-plugins]     list all available plugin
+  [--disable <plugin>] do not compile given plugin (3)
+  [-I <includes_dir>]  add extra include directory to compilation (3)
+  [-L <libs_dir>]      add extra library directory to linking (3)
+  [--help]             show this helpful text
+
+(1) does not require recompilation
+(2) make binary slower and much larger (~30 times)
+(3) can be specified multiple times
+EOF
   exit 1
 }
+
+# compile (but do not link)
+function compile()
+{
+  gcc -c -o /dev/null "$1" $EXTRA_COMPILE_FLAGS > /dev/null 2>&1
+  return "$?"
+}
+
 
 #
 # process command line options
@@ -50,6 +73,16 @@ do
       exit 0
     ;;
 
+    "-I")
+      EXTRA_COMPILE_FLAGS="$EXTRA_COMPILE_FLAGS -I $2"
+      shift
+    ;;
+
+    "-L")
+      EXTRA_LINK_FLAGS="$EXTRA_LINK_FLAGS -L $2"
+      shift
+    ;;
+
     "--help")
       print_help
     ;;
@@ -61,6 +94,7 @@ do
   shift
 done
 
+
 #
 # select features to build with
 #
@@ -69,7 +103,7 @@ TMP="`mktemp --suffix=.cpp`"
 # TEST: boost::filesystem version
 echo -n "checking for new boost::filesystem version... "
 echo -e "#include <boost/filesystem.hpp>\nusing boost::filesystem::is_regular_file;" > "$TMP"
-if gcc -c "$TMP" -o /dev/null > /dev/null 2>&1
+if compile "$TMP"
 then
   echo "got new boost"
   FEATURES="$FEATURES use_new_boost_filesystem"
@@ -77,7 +111,7 @@ else
   echo "N/A"
   echo -n "checking for old boost::filesystem version... "
   echo -e "#include <boost/filesystem.hpp>\nusing boost::filesystem::is_regular;" > "$TMP"
-  if gcc -c "$TMP" -o /dev/null > /dev/null 2>&1
+  if compile "$TMP"
   then
     echo "got old boost"
     FEATURES="$FEATURES use_old_boost_filesystem"
@@ -89,17 +123,24 @@ else
   fi
 fi
 
+# cleanup
+rm -f "$TMP"
+
 
 #
 # prepare proper make entries
 #
+
+# prepare main makefile elements
 cat<<EOF > configure-output.mk
 NCPUS:=\$(shell cat /proc/cpuinfo | grep 'processor.*:' | wc -l)
 
 .PHONY: build
 build: build-core build-plugins
 
-LOCAL_MAKE_FLAGS:=-C src --no-print-directory PROFILE=$PROFILE "FEATURES=$FEATURES" TC=gcc -j '\$(NCPUS)'
+LOCAL_MAKE_FLAGS:=-C src --no-print-directory -j '\$(NCPUS)'
+LOCAL_MAKE_FLAGS+=PROFILE=$PROFILE "FEATURES=$FEATURES" TC=gcc
+LOCAL_MAKE_FLAGS+="EXTRA_COMPILE_FLAGS=$EXTRA_COMPILE_FLAGS" "EXTRA_LINK_FLAGS=$EXTRA_LINK_FLAGS"
 
 .PHONY: build-core
 build-core: configure
@@ -160,11 +201,14 @@ install-plugins: install-libs
 	done
 EOF
 
+
 #
 # display summary
 #
+echo
 echo "SUMMARY:"
 echo "  prefix:   $PREFIX"
 echo "  profile:  $PROFILE"
 echo "  plugins:  `echo "$PLUGINS" | xargs -r echo -n`"
 echo "  features: $FEATURES"
+echo
