added print-out for groups that failed.
modified:
  src/run_all_tests
  src/run_all_tests_leak_check

diff --git a/src/run_all_tests b/src/run_all_tests
--- a/src/run_all_tests
+++ b/src/run_all_tests
@@ -13,7 +13,11 @@ for d in `cat build_config/components{.,_test.}lst | sort | uniq | grep -v '^pre
 do
   echo "----------------------------"
   echo "testing $d:"
-  ( ulimit -c unlimited && cd gen/test_${TC}_${MEM_MODE}_default/$d && LD_LIBRARY_PATH="$LD_LIBRARY_PATH:../libs/" ./$d.t ) || RET=1
+  if ! ( ulimit -c unlimited && cd gen/test_${TC}_${MEM_MODE}_default/$d && LD_LIBRARY_PATH="$LD_LIBRARY_PATH:../libs/" ./$d.t )
+  then
+    RET=1
+    echo "$d group FAILED"
+  fi
 done
 
 echo
