data base initializaiton scripts now take UI/daemon password files as an arguments.
removed:
  data_model/postgres/8.3/10_create_accounts.sql
  data_model/postgres/8.4/10_create_accounts.sql
added:
  data_model/postgres/8.3/tests/daemon_pass
  data_model/postgres/8.3/tests/ui_pass
  data_model/postgres/8.4/tests/daemon_pass
  data_model/postgres/8.4/tests/ui_pass
modified:
  data_model/postgres/init_db
  data_model/postgres/init_test_db

diff --git a/data_model/postgres/init_db b/data_model/postgres/init_db
--- a/data_model/postgres/init_db
+++ b/data_model/postgres/init_db
@@ -1,8 +1,43 @@
 #!/bin/bash
-DB="acarm_ng"
 
+# check syntax
+if [ "$#" -ne "3" ]
+then
+  echo "$0 <dbname> <daemon_passwd_file> <ui_passwd_file>" >&2
+  exit 1
+fi
+
+DB="$1"
+PASSF_UI="$2"
+PASSF_DMN="$3"
+
+# ensure porper user
+if ! psql -d "$DB" -w -c '\q' > /dev/null 2>&1
+then
+  echo "$0: cannot access data base $DB as $USER" >&2
+  exit 2
+fi
+
+# drop current content
 # note: 'ls' is needed here to preserve proper order of execution
-for s in `ls *.sql`
+for s in `ls 0*.sql`
 do
-  psql -d "$DB" -f $s || exit $?
+  psql -w -d "$DB" -f $s > /dev/null 2>&1
 done
+
+# create users
+MKUSERS="`mktemp`"
+# create accounts creation script
+echo "CREATE USER \"acarm-ng-daemon\" PASSWORD '$(cat "$PASSF_DMN")';" >> "$MKUSERS"
+echo "CREATE USER \"acarm-ng-ui\"     PASSWORD '$(cat "$PASSF_UI")' ;" >> "$MKUSERS"
+psql -w -d "$DB" -f $MKUSERS || exit $?
+rm "$MKUSERS"
+
+# create new content
+# note: 'ls' is needed here to preserve proper order of execution
+for s in `ls [^0]*.sql`
+do
+  psql -w -d "$DB" -f $s || exit $?
+done
+
+exit 0
