moved back to old, working version.
modified:
  data_model/postgres/8.4/tests/create_test_user.sql
  data_model/postgres/init_db
  data_model/postgres/init_test_db

diff --git a/data_model/postgres/init_db b/data_model/postgres/init_db
--- a/data_model/postgres/init_db
+++ b/data_model/postgres/init_db
@@ -11,16 +11,30 @@ DB="$1"
 PASSF_DMN="$2"
 PASSF_UI="$3"
 
+# ensure porper user
+if ! psql -d "$DB" -w -c '\q' > /dev/null 2>&1
+then
+  echo "$0: cannot access data base $DB as $USER" >&2
+  exit 2
+fi
+
 #
 # drop current content
 #
 
-MKDB="`mktemp`"
-# script creating data base
-echo "DROP   DATABASE \"$DB\";" >> "$MKDB"
-echo "CREATE DATABASE \"$DB\";" >> "$MKDB"
-psql -w -f "$MKDB" || exit $?
-rm "$MKDB"
+MKUSERS="`mktemp`"
+# script revoking permissions of connecting for a given users
+echo "REVOKE CONNECT ON DATABASE \"$DB\" FROM \"acarm-ng-daemon\";" >> "$MKUSERS"
+echo "REVOKE CONNECT ON DATABASE \"$DB\" FROM \"acarm-ng-ui\";"     >> "$MKUSERS"
+psql -w -d "$DB" -f $MKUSERS > /dev/null 2>&1 || exit $?
+rm "$MKUSERS"
+
+# run remaining clean-up scripts
+# note: 'ls' is needed here to preserve proper order of execution
+for s in `ls 0*.sql`
+do
+  psql -w -d "$DB" -f $s > /dev/null 2>&1
+done
 
 #
 # fill with new data
@@ -29,7 +43,6 @@ rm "$MKDB"
 # create users
 MKUSERS="`mktemp`"
 # script creating accounts, giving them ability to connect
-echo "CREATE LANGUAGE plpgsql;"                                        >> "$MKUSERS"
 echo "CREATE USER \"acarm-ng-daemon\" PASSWORD '$(cat "$PASSF_DMN")';" >> "$MKUSERS"
 echo "CREATE USER \"acarm-ng-ui\"     PASSWORD '$(cat "$PASSF_UI")';"  >> "$MKUSERS"
 echo "GRANT CONNECT ON DATABASE \"$DB\" to \"acarm-ng-daemon\";"       >> "$MKUSERS"
